name: Build and Test

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      TEST_API_URL: ${{ secrets.TEST_API_URL }}
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
      TEST_DB_WORKSPACE_ID:  ${{ secrets.TEST_DB_WORKSPACE_ID }}
      TEST_DB_DESIGN_SYSTEM_ID: ${{ secrets.TEST_DB_DESIGN_SYSTEM_ID }}
      TEST_DB_DESIGN_SYSTEM_VERSION_ID: ${{ secrets.TEST_DB_DESIGN_SYSTEM_VERSION_ID }}
      TEST_DB_DESIGN_SYSTEM_ID_EDIT: ${{ secrets.TEST_DB_DESIGN_SYSTEM_ID_EDIT }}
      TEST_DB_DESIGN_SYSTEM_VERSION_ID_EDIT: ${{ secrets.TEST_DB_DESIGN_SYSTEM_VERSION_ID_EDIT }}
      TEST_DB_UNKNOWN_ID: 998877

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Build and Test
      #   run: npm run test